* Path of the badges metadata were found successfully

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -34,18 +34,45 @@ jobs:
     #     pipenv run lint
     - name: Test with pytest
       run: |
+        echo "TESTS_PASSED=false" >> $GITHUB_ENV
         pipenv run unit
-        pipenv run coverage_json
+        echo "TESTS_PASSED=true" >> $GITHUB_ENV
     - name: Count coverage
       run: |
         echo "COVERAGE=$(pipenv run coverage | awk '$1 == "TOTAL" {print $NF+0}')" >> $GITHUB_ENV
+#    - name: Create Linters Badge
+#      uses: schneegans/dynamic-badges-action@v1.6.0
+#      with:
+#        auth: ${{ secrets.GIST_SECRET }}
+#        gistID: e8d23650144c1dd611a941789d52721a
+#        filename: coverage.json
+#        label: Linting
+#        message: ${{ env.COVERAGE }}
+#        namedLogo: pytest
+#        logoColor: lightblue
+#        valColorRange: ${{ env.COVERAGE }}
+#        maxColorRange: 100
+#        minColorRange: 50
+    - name: Create Test Pass Badge
+      uses: schneegans/dynamic-badges-action@v1.6.0
+      with:
+        auth: ${{ secrets.GIST_SECRET }}
+        gistID: e8d23650144c1dd611a941789d52721a
+        filename: tic-tac-toe__tests_passed.json
+        label: Tests
+        message: ${{ env.TESTS_PASSED && echo "PASSED" || echo "FAILED" }}
+        namedLogo: pytest
+        logoColor: lightblue
+        valColorRange: ${{ env.TESTS_PASSED && echo 100 || echo 0 }}
+        maxColorRange: 100
+        minColorRange: 50
     - name: Create Coverage Badge
       uses: schneegans/dynamic-badges-action@v1.6.0
       with:
         auth: ${{ secrets.GIST_SECRET }}
         gistID: e8d23650144c1dd611a941789d52721a
-#        filename: coverage.json
-        label: Test Coverage
+        filename: tic-tac-toe__coverage.json
+        label: Lines Coverage
         message: ${{ env.COVERAGE }}
         namedLogo: pytest
         logoColor: lightblue
